/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class DishStackTest {

    @Test
    public void testInitialSizeIsZero() {
        DishStack stack = new DishStack();
        assertEquals(0, stack.size());
    }

    @Test
    public void testPushIncreasesSize() {
        DishStack stack = new DishStack();
        stack.push(new Dish("One"));
        stack.push(new Dish("Two"));
        assertEquals(2, stack.size());
    }

      @Test
    public void testPopOnEmptyReturnsNull() {
        DishStack stack = new DishStack();
        assertNull(stack.pop());
    }

    @Test
    public void testPeekOnEmptyReturnsNull() {
        DishStack stack = new DishStack();
        assertNull(stack.peek());
    }

     @Test
    public void testPushOnFullStackDoesNotIncreaseSize() {
        DishStack stack = new DishStack(2);
        stack.push(new Dish("One"));
        stack.push(new Dish("Two"));
        stack.push(new Dish("Three")); // Should not be added

        assertEquals(2, stack.size());
        assertEquals("Two", stack.peek().description);
    }
}